// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GraphIt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GraphIt",
            targets: ["AppModule"],
            bundleIdentifier: "com.jaagrav.GraphIt",
            teamIdentifier: "89659343H8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/stevengharris/SplitView.git", "3.5.2"..<"4.0.0"),
        .package(url: "https://github.com/dwarvesf/CodeViewer.git", "1.2.4"..<"2.0.0"),
        .package(url: "https://github.com/gonzalezreal/swift-markdown-ui", "2.3.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SplitView", package: "splitview"),
                .product(name: "CodeViewer", package: "codeviewer"),
                .product(name: "MarkdownUI", package: "swift-markdown-ui")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)